### ISSUE TITLE
ErrorException: Undefined index: provider

### ISSUE THREAD

**Issue by redbayoub** [laravel/sanctum#210]
- Sanctum Version: 2.7
- Laravel Version: 7.22.4
- PHP Version: 7.2.19 
- Database Driver & Version: MySql 

### Description:
I get error after installing sanctum and navigating to any route using postman
```
ErrorException: Undefined index: provider in file C:\laragon\www\hair-salon\vendor\laravel\sanctum\src\SanctumServiceProvider.php on line 115

#0 C:\laragon\www\hair-salon\vendor\laravel\sanctum\src\SanctumServiceProvider.php(115): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', 'C:\\laragon\\www\\...', 115, Array)
#1 C:\laragon\www\hair-salon\vendor\laravel\sanctum\src\SanctumServiceProvider.php(98): Laravel\Sanctum\SanctumServiceProvider->createGuard(Object(Illuminate\Auth\AuthManager), Array)
#2 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Auth\AuthManager.php(111): Laravel\Sanctum\SanctumServiceProvider->Laravel\Sanctum\{closure}(Object(Illuminate\Foundation\Application), 'api', Array)
#3 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Auth\AuthManager.php(88): Illuminate\Auth\AuthManager->callCustomCreator('api', Array)
#4 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Auth\AuthManager.php(68): Illuminate\Auth\AuthManager->resolve('api')
#5 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Auth\AuthManager.php(54): Illuminate\Auth\AuthManager->guard('api')
#6 [internal function]: Illuminate\Auth\AuthManager->Illuminate\Auth\{closure}(NULL)
#7 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Auth\AuthServiceProvider.php(106): call_user_func(Object(Closure), NULL)
#8 [internal function]: Illuminate\Auth\AuthServiceProvider->Illuminate\Auth\{closure}(NULL)
#9 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Http\Request.php(518): call_user_func(Object(Closure), NULL)
#10 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Routing\Middleware\ThrottleRequests.php(97): Illuminate\Http\Request->user()
#11 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Routing\Middleware\ThrottleRequests.php(49): Illuminate\Routing\Middleware\ThrottleRequests->resolveRequestSignature(Object(Illuminate\Http\Request))
#12 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), '30', '1')
#13 C:\laragon\www\hair-salon\vendor\laravel\sanctum\src\Http\Middleware\EnsureFrontendRequestsAreStateful.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful->Laravel\Sanctum\Http\Middleware\{closure}(Object(Illuminate\Http\Request))
#15 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 C:\laragon\www\hair-salon\vendor\laravel\sanctum\src\Http\Middleware\EnsureFrontendRequestsAreStateful.php(34): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Routing\Router.php(687): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Routing\Router.php(662): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#21 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Routing\Router.php(628): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#22 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Routing\Router.php(617): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#23 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(165): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#24 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#25 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 C:\laragon\www\hair-salon\vendor\fruitcake\laravel-cors\src\HandleCors.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fruitcake\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 C:\laragon\www\hair-salon\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(140): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 C:\laragon\www\hair-salon\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(109): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#40 C:\laragon\www\hair-salon\public\index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#41 C:\laragon\www\hair-salon\server.php(21): require_once('C:\\laragon\\www\\...')
#42 {main}
```

### Steps To Reproduce:
composer require laravel/sanctum

php artisan vendor:publish --provider="Laravel\Sanctum\SanctumServiceProvider"

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
